version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"  # HTTPS порт
      - "3000:3000"  # HTTP порт (fallback)
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/email_generator
      - SSL_KEY_PATH=/app/ssl/private.key
      - SSL_CERT_PATH=/app/ssl/certificate.crt
      - JWT_SECRET=your-secret-key-change-in-production
      - GEMINI_API_KEY=your-gemini-api-key-here
    depends_on:
      - postgres
    volumes:
      - ./frontend:/app/frontend
      - ./uploads:/app/uploads
      - ./src:/app/src
    restart: unless-stopped
    user: "1001:1001"

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=email_generator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: